name: Clean notebooks

on: [push]

jobs:
  clean-notebooks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
      with:
        disable-checks: outputs,execution_count

