name: Clear notebooks

on: [push]

jobs:
  clear-notebooks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: "treebeardtech/nbmake-action@v0.2"
      with:
        path: "./models/ARIMA"
    - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
      with:
        disable-checks: outputs,execution_count

